repos:
   - repo: https://github.com/gvanderest/pylama-pre-commit
     rev: 0.1.2
     hooks:
     - id: pylama

   - repo: https://github.com/d-ryzhikov/pipenv-lock-pre-commit
     rev: 0.1.0
     hooks:
     - id: pipenv-lock
